### ISSUE TITLE
detect installed libraries/sources to avoid unnecessary steps

### ISSUE THREAD

**Issue by twojstaryzdomu** [roc-streaming/roc-pulse#1]
It should be possible to detect a library and its sources are installed locally without the added need to download libasound, libsndfile, libtool and jsonc. Each step takes time.
It's far quicker to install those via a distribution-based mechanism (deb,rpm etc.) than wait until those download & compile.
Also, compiling pulseaudio isn't strictly necessary either, only configuring it so that config.h is generated.

**Comment by gavv** [comment]
Thanks, noted. Will fix it.

**Comment by gavv** [comment]
Not relevant now: see https://github.com/roc-streaming/roc-toolkit/pull/458#issuecomment-922261872
