### ISSUE TITLE
Pulseaudio sending config does not honor sample rate

### ISSUE THREAD

**Issue by Kaspi314** [roc-streaming/roc-pulse#14]
When sending from pulse audio (Ubuntu 20 LTS Desktop) with resampling in PA Daemon config to 48000hz 2channel f16, setting is not honored or configurable for the PA module and it will not connect to Raspberry Pi ALSA session.

With 44100hz there is an inability for the resampler to keep up even on LOW with the Pi 4:

`22:01:05.473 [dbg] roc_packet: router: detected new stream: source=1807046489 flags=0x8u

22:01:05.473 [dbg] roc_audio: depacketizer: ts=320 loss_ratio=0.00000

22:01:05.513 [dbg] roc_packet: router: detected new stream: source=0 flags=0x10u

22:01:05.593 [dbg] roc_audio: watchdog: status: bbbbbbbbbbbbbbbbbbbb

22:01:05.663 [dbg] roc_packet: delayed reader: initial queue: delay=8820 queue=8961 packets=29

22:01:05.663 [dbg] roc_fec: fec reader: update payload size: next_esi=0 cur_size=0 new_size=1248

22:01:05.663 [dbg] roc_fec: fec reader: update source block size: cur_sblen=0 cur_rblen=0 new_sblen=20

22:01:05.663 [dbg] roc_audio: depacketizer: got first packet: zero_samples=8960

22:01:05.663 [dbg] roc_audio: latency monitor: latency=8641 target=8820 fe=1.00000 trim_fe=1.00000 adj_fe=0.91875

22:01:05.703 [dbg] roc_fec: fec reader: repair queue: dropped=10

22:01:05.703 [dbg] roc_fec: fec reader: got first packet in a block, start decoding: n_packets_before=7 sbn=31405

22:01:05.703 [dbg] roc_fec: fec reader: update repair block size: cur_sblen=20 cur_rblen=0 new_rblen=235

22:01:05.743 [dbg] roc_audio: watchdog: status: bbbbbbbb............

22:01:10.673 [dbg] roc_audio: latency monitor: latency=9085 target=8820 fe=1.00000 trim_fe=1.00000 adj_fe=0.91875

22:01:15.673 [dbg] roc_audio: latency monitor: latency=9231 target=8820 fe=1.00002 trim_fe=1.00002 adj_fe=0.91877
`

**Comment by gavv** [comment]
It's now possible to configure both network encoding and local sink/sink-input encoding. See parameters tables in README, in particular `packet_encoding_xxx`, `sink_xxx`, and `sink_input_xxx` parameters.

If local and network encodings do not match, roc will perform conversion.

Currently there is only limited set of formats and channel layouts, more to be added in future releases.

I'm closing the issue, but feel free to reopen if needed.
